version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: pswd
       MYSQL_DATABASE: idintegrator
       MYSQL_USER: idintegrator
       MYSQL_PASSWORD: pswd
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
      - ./:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: idintegrator
       WORDPRESS_DB_PASSWORD: pswd
       WORDPRESS_DB_NAME: idintegrator
volumes:
    db_data:
