version: '3.3'

services:
  db:
    image: mysql:latest
    #image: mysql:5.7
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "db:${DB_PORT}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
volumes:
  db_data:
